const PREFIX_GROUP_NOTIFY_SETTING = "/group_notify_setting";

export const API_GROUP_NOTIFY_SETTING_ROUTERS = {
  GET: {
    GROUP_NOTIFY_SETTING_GET: `${PREFIX_GROUP_NOTIFY_SETTING}/action/get/{slug}`,
    GROUP_NOTIFY_SETTING_GETLIST: `${PREFIX_GROUP_NOTIFY_SETTING}/action/getlist`,
  },
  POST: {
    GROUP_NOTIFY_SETTING_CREATE_ONE: `${PREFIX_GROUP_NOTIFY_SETTING}/action/create`,
  },
  PUT: {
    GROUP_NOTIFY_SETTING_UPDATE_ONE: `${PREFIX_GROUP_NOTIFY_SETTING}/action/update/{id}`,
  },
  DELETE: {
    GROUP_NOTIFY_SETTING_DELETE_ONE: `${PREFIX_GROUP_NOTIFY_SETTING}/action/delete/{id}`,
  },
};
