const PREFIX_DISCUSSION_COMMENT = "/discussion_comment";

export const API_DISCUSSION_COMMENT_ROUTERS = {
  GET: {
    DISCUSSION_COMMENT_GET: `${PREFIX_DISCUSSION_COMMENT}/action/get/{slug}`,
    DISCUSSION_COMMENT_GETLIST: `${PREFIX_DISCUSSION_COMMENT}/action/getlist`,
  },
  POST: {
    DISCUSSION_COMMENT_CREATE_ONE: `${PREFIX_DISCUSSION_COMMENT}/action/create`,
    DISCUSSION_COMMENT_LIKE: `${PREFIX_DISCUSSION_COMMENT}/action/like`,
  },
  PUT: {
    DISCUSSION_COMMENT_UPDATE_ONE: `${PREFIX_DISCUSSION_COMMENT}/action/update/{id}`,
  },
  DELETE: {
    DISCUSSION_COMMENT_DELETE_ONE: `${PREFIX_DISCUSSION_COMMENT}/action/delete/{id}`,
  },
};
