const PREFIX_DISCUSSION_COMMENT_LIKE = "/discussion_comment_like";

export const API_DISCUSSION_COMMENT_LIKE_ROUTERS = {
  GET: {
    DISCUSSION_COMMENT_LIKE_GET: `${PREFIX_DISCUSSION_COMMENT_LIKE}/action/get/{slug}`,
    DISCUSSION_COMMENT_LIKE_GETLIST: `${PREFIX_DISCUSSION_COMMENT_LIKE}/action/getlist`,
  },
};
