const PREFIX_SOCIAL_EVENT_REGISTRATION = "/social_event_registration";

export const API_SOCIAL_EVENT_REGISTRATION_ROUTERS = {
  GET: {
    SOCIAL_EVENT_REGISTRATION_GET: `${PREFIX_SOCIAL_EVENT_REGISTRATION}/action/get/{slug}`,
    SOCIAL_EVENT_REGISTRATION_GETLIST: `${PREFIX_SOCIAL_EVENT_REGISTRATION}/action/getlist`,
  },
};
